### ISSUE TITLE
Update for Iceborne DLC game ver. 10.12.00 please

### ISSUE THREAD

**Issue by Holair** [r00telement/SmartHunter#24]
Hi! Overlay is not starting up with new Iceborne Ver. 10.12.00. Could you fix it please?
![uholPXJ](https://user-images.githubusercontent.com/11192806/72112897-01463500-3350-11ea-8570-34d6fc6bcc78.png)

**Comment by dannylin0711** [comment]
I think the memory pattern is defined in the Memory.json ,if you find the new memory pattern you can fill it into the Memory.json.

**Comment by Holair** [comment]
> I think the memory pattern is defined in the Memory.json ,if you find the new memory pattern you can fill it into the Memory.json.

And how to find it?

**Comment by Elec0** [comment]
I found `PlayerDamagePattern` at
```
matchAddress: 5394035031
```

I have not yet found anything else, even scanning over a very large amount of memory.

**Comment by trim21** [comment]
@Holair use https://www.nexusmods.com/users/58674841 and `cheat engine`

**Comment by NevanNedall** [comment]
> @Holair use https://www.nexusmods.com/users/58674841 and `cheat engine`

HelloWorld, frankly, is way more complicated to set up the way you want it than SmartHunter, and IMO, looks worse. I'd much rather see SmartHunter get updated, especially since all I care about is team damage and buffs UI.

While it admittedly has more features, with that comes added difficulty in configuring it, especially if someone's never seen a config file before.

**Comment by trim21** [comment]
@NevanNedall agree with you, I prefer S martHunter.
I mean you can use helloworld and ce to find memory pattern and update smarthunter, it’s an answer of “ And how to find it?”

**Comment by X-Vaskys** [comment]
> I mean you can use helloworld and ce to find memory pattern and update smarthunter

How to do so? Not sure how to use CE

**Comment by trim21** [comment]
@MS21GH I'm not a native English speaker, there should be some Engling articles about it.

**Comment by NevanNedall** [comment]
@Trim21 Oh I see, my mistake

**Comment by X-Vaskys** [comment]
@Trim21 What exactly should I look for?

**Comment by gabrielefilipp** [comment]
Hey guys i forked SmartHunter (https://github.com/gabrielefilipp/SmartHunter) and i'm trying to make it works again. So far PlayerDamage, MonsterData and an initial state of MonsterParts is working. If you find something interesting please le me know :)

**Comment by kai-oswald** [comment]
Hey @gabrielefilipp,
looks good on a first glance!
How did you go about finding the new memory patterns? Just with CE?

**Comment by gabrielefilipp** [comment]
Hey @kai-oswald,
yeah with CE and other DPS Meter open to calculate new offsets.

**Comment by NevanNedall** [comment]
@gabrielefilipp perhaps I'm just stupid but how do you actually download the program, and not the project files.

**Comment by NevanNedall** [comment]
@gabrielefilipp
Perhaps I'm just stupid.. but where do you get the actual EXE? I've always had trouble remembering how to properly download things off git

**Comment by X-Vaskys** [comment]
If you're trying to download Smart Hunter, it's on the NexusMods page; same
thing goes for HelloWorld

**Comment by NevanNedall** [comment]
The new branched version of it is also on Nexus?

**Comment by X-Vaskys** [comment]
Sorry no I misread:
The forked version is on the GitHub page, just click on "Clone or
Download", that should do it

**Comment by NevanNedall** [comment]
I did that. There is no .exe present.
Edit: Well, I did find an exe in bin > x64 > Debug, but nothing happens when it's launched, but I suppose at that point I should bring it up on that project.

**Comment by gabrielefilipp** [comment]
@NevanNedall here: https://github.com/gabrielefilipp/SmartHunter/blob/master/SmartHunter/bin/x64/Debug/SmartHunter.exe. Also remember that it's pretty buggy for a better meter use HelloWorld

**Comment by X-Vaskys** [comment]
Not at my PC so I can't check; maybe you could just be able to put the new
files in the outdated version and try launching the program again? Not sure

**Comment by aklein13** [comment]
@NevanNedall When I lunch debug version it takes a while to load (5-10 sec?) and it's using more CPU then the game itself during the load. That is to be expected behaviour because it's a debug version not meant for normal use. 
To get a good working exe can either compile it or use mine compiled version: https://drive.google.com/open?id=1nivyAgxPBPkRmFG6Bpy2Y_L9LeXVgv0a

Anyway I got it up and working: https://i.imgur.com/p6OZgqB.jpg

**Comment by hsaldanha** [comment]
> Hey guys i forked SmartHunter (https://github.com/gabrielefilipp/SmartHunter) and i'm trying to make it works again. So far PlayerDamage, MonsterData and an initial state of MonsterParts is working. If you find something interesting please le me know :)

@gabrielefilipp Thanks for working on this one. I've been trying to fix this since Iceborne came out but I don't have as much time as I wanted to invest, so no progress yet. I'll see if I can help you.

**Comment by Toukassay** [comment]
> @NevanNedall When I lunch debug version it takes a while to load (5-10 sec?) and it's using more CPU then the game itself during the load. That is to be expected behaviour because it's a debug version not meant for normal use.
> To get a good working exe can either compile it or use mine compiled version: https://drive.google.com/open?id=1nivyAgxPBPkRmFG6Bpy2Y_L9LeXVgv0a
> 
> Anyway I got it up and working: https://i.imgur.com/p6OZgqB.jpg

I don't know why I can launch your version but not the forked one from https://github.com/gabrielefilipp/SmartHunter
From this depot, it just don't launch. Nothing happen after clicking it. Yours worked like a charm. Strange.

**Comment by Toukassay** [comment]
> I did that. There is no .exe present.
> Edit: Well, I did find an exe in bin > x64 > Debug, but nothing happens when it's launched, but I suppose at that point I should bring it up on that project.

Well, same

**Comment by gabrielefilipp** [comment]
You need to have "Newtonsoft.Json.dll" file in the same folder with the .exe... If you don't have it just download the original version and then replace the new .exe

**Comment by scorpion21b** [comment]
player data widget isn't working

**Comment by gabrielefilipp** [comment]
@scorpion21b  Player names and damages are correctly show. As for Player Buffs, yeah it's not working yet (like monster removable parts and monsters status effects)

**Comment by morsley** [comment]
@gabrielefilipp Hey, in your fork - why don't you compile everything down to a single exe using .net core 3.1 or something?  Would make distribution easier and there are a lot of perfomance gains seen there (WPF && WinForms work on Core 3.x+ now for Windows targets)

**Comment by gabrielefilipp** [comment]
@TheIncorrigible1  There's one compiled version under https://github.com/gabrielefilipp/SmartHunter/blob/master/SmartHunter/bin/x64/Debug/SmartHunter.exe

**Comment by morsley** [comment]
@gabrielefilipp I have built it myself 🙂 I was just making a suggestion for improvement.

**Comment by masterrite** [comment]
@gabrielefilipp I got this when launching your forked version - any help here? Thanks:

```
JsonReaderException: Invalid property identifier character: �. Path 'Strings.LOC_MONSTER_GLAVENUS', line 18, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
```

**Comment by gabrielefilipp** [comment]
It says that there is an invalid character inside a file. Try to remove every json file inside the directory and restart SmartHunter.exe

**Comment by davy-tw** [comment]
@gabrielefilipp I got permission denied while executing gabrielefilipp/SmartHunter

```
[2020-02-01 09:03:38] State Machine: CheckingForUpdates (2977 ms) > WaitingForProcess
[2020-02-01 09:03:38] Win32Exception: 存取被拒。
   於 System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   於 System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   於 System.Diagnostics.Process.get_HasExited()
   於 SmartHunter.Core.MemoryUpdater.<>c__DisplayClass19_0.<CreateStateMachine>b__14()
   於 SmartHunter.Core.StateMachine`1.Update()
   於 SmartHunter.Core.MemoryUpdater.Update(Object sender, EventArgs e)
```

And would you open the issue tracker on your forked repo, or just reporting issues here?

--

UPDATE: "Open with administrator" works with this fork, but I don't want to run this application as admin (and the original application doesn't need either), can this be fixed?

**Comment by masterrite** [comment]
> @gabrielefilipp I got permission denied while executing gabrielefilipp/SmartHunter
> 
> ```
> [2020-02-01 09:03:38] State Machine: CheckingForUpdates (2977 ms) > WaitingForProcess
> [2020-02-01 09:03:38] Win32Exception: 存取被拒。
>    於 System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
>    於 System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
>    於 System.Diagnostics.Process.get_HasExited()
>    於 SmartHunter.Core.MemoryUpdater.<>c__DisplayClass19_0.<CreateStateMachine>b__14()
>    於 SmartHunter.Core.StateMachine`1.Update()
>    於 SmartHunter.Core.MemoryUpdater.Update(Object sender, EventArgs e)
> ```
> 
> And would you open the issue tracker on your forked repo, or just reporting issues here?

right click and properties and set to run as admin

**Comment by davy-tw** [comment]
@masterrite thanks, but I don't want this application run as admin, the original (r00telement's) SmartHunter doesn't need admin permission either.

**Comment by gabrielefilipp** [comment]
Is your system 32 bit?

**Comment by davy-tw** [comment]
@gabrielefilipp 64bit Windows 10 18362.267

**Comment by gabrielefilipp** [comment]
@david50407 strange mine does not require an admin run

**Comment by trim21** [comment]
Maybe not a bug, but depending on how you start your steam and mhw. I sometimes have same problems with other overlay tools



------------------ Original ------------------

**Comment by davy-tw** [comment]
@Trim21 How do you start steam and mhw?
I closed steam and restart until it won't get auto-updated then start mhw from steam

@gabrielefilipp The wired thing is while mhw is not running, this permission denied exception still happened, that means `process` is not null, and there is a special Process instance (may created by `Process[].FirstOrDefault`?) which has higher permission causing permission denied

https://github.com/gabrielefilipp/SmartHunter/blob/master/SmartHunter/Core/MemoryUpdater.cs#L153

**Comment by davy-tw** [comment]
Maybe we can just skip the exception and try to match all processes in the Process array?
And print the "Start MHW or Run As Admin" message if none of them are matched?

**Comment by gabrielefilipp** [comment]
@david50407 I've pushed an update, can you try if that works?

**Comment by davy-tw** [comment]
@gabrielefilipp yes that works, thank you.

**Comment by dannylin0711** [comment]
The team widget is broken again

**Comment by gabrielefilipp** [comment]
> The team widget is broken again

Yeah I know. Also rage status is broken. I’ve already fixed those but I’m currently experimenting with the buff widget so I’ll push when I’ve made it work again :)
