### ISSUE TITLE
InvalidOperationException: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by jhillacre** [r00telement/SmartHunter#32]
Saw this traceback, probably related to the new client version.

```
[2020-02-06 04:08:21] InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at SmartHunter.Game.Helpers.MhwHelper.UpdateMonsterStatusEffects(Process process, Monster monster)
   at SmartHunter.Game.Helpers.MhwHelper.UpdateAndGetMonster(Process process, UInt64 monsterAddress)
   at SmartHunter.Game.Helpers.MhwHelper.UpdateMonsterWidget(Process process, UInt64 monsterBaseList)
   at SmartHunter.Game.MhwMemoryUpdater.UpdateMemory()
   at SmartHunter.Core.MemoryUpdater.<>c__DisplayClass19_0.<CreateStateMachine>b__23()
[2020-02-06 04:08:23] InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at SmartHunter.Game.Helpers.MhwHelper.UpdateMonsterStatusEffects(Process process, Monster monster)
   at SmartHunter.Game.Helpers.MhwHelper.UpdateAndGetMonster(Process process, UInt64 monsterAddress)
   at SmartHunter.Game.Helpers.MhwHelper.UpdateMonsterWidget(Process process, UInt64 monsterBaseList)
   at SmartHunter.Game.MhwMemoryUpdater.UpdateMemory()
   at SmartHunter.Core.MemoryUpdater.<>c__DisplayClass19_0.<CreateStateMachine>b__23()
```

**Comment by jhillacre** [comment]
Occurs when the first monster dies on `Every Hunter's Dream III`.
